apiVersion: v1
kind: Secret
metadata:
  name: grpcsecret
  namespace: newsfeed
type: Opaque
data:
  DB_CONN: ${DB_CONN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grpcconfigmap
  namespace: newsfeed
data:
  GRPC_PORT: "9000"
  OTEL_SERVICE_NAME: "newsfeed-grpc"
  OTEL_EXPORTER_OTLP_GRPC_ENDPOINT: "192.168.1.6:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: newsfeed-grpc
  namespace: newsfeed
  labels:
    app: newsfeed-grpc
spec:
  type: NodePort
  ports:
  - port: 9000
    name: grpc
    targetPort: 9000
    nodePort: 30008
    protocol: TCP
  - port: 9001
    name: metrics
    targetPort: 9001
    nodePort: 30009
    protocol: TCP
  selector:
    app: newsfeed-grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-grpc
  namespace: newsfeed
  labels:
    app: newsfeed-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newsfeed-grpc
  template:
    metadata:
      labels:
        app: newsfeed-grpc
    spec:
      containers:
      - name: newsfeed-grpc
        image: edisonlt/grpc-feed:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: grpcsecret
              key: DB_CONN
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: grpcsecret
              key: OTEL_SERVICE_NAME
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: grpcconfigmap
              key: GRPC_PORT
        - name: OTEL_EXPORTER_OTLP_GRPC_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: grpcconfigmap
              key: OTEL_EXPORTER_OTLP_GRPC_ENDPOINT
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /live
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 30
