apiVersion: v1
kind: Secret
metadata:
  name: websecret
  namespace: newsfeed
type: Opaque
data:
  HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webconfigmap
  namespace: newsfeed
data:
  GRPC_SERVER_ADDRESS: 192.168.1.7:30008
  WEB_PORT: "5000"
  HEALTH_CHECK_PORT: "8086"
  OTEL_SERVICE_NAME: "newsfeed-web"
---
apiVersion: v1
kind: Service
metadata:
  name: newsfeed-web
  namespace: newsfeed
  labels:
    app: newsfeed-web
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30010
    protocol: TCP
  selector:
    app: newsfeed-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-web
  namespace: newsfeed
  labels:
    app: newsfeed-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newsfeed-web
  template:
    metadata:
      labels:
        app: newsfeed-web
    spec:
      containers:
      - name: newsfeed-web
        image: edisonlt/web-feed:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: GRPC_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: webconfigmap
              key: GRPC_SERVER_ADDRESS
        - name: WEB_PORT
          valueFrom:
            configMapKeyRef:
              name: webconfigmap
              key: WEB_PORT
        - name: HEALTH_CHECK_PORT
          valueFrom:
            configMapKeyRef:
              name: webconfigmap
              key: HEALTH_CHECK_PORT
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: webconfigmap
              key: OTEL_SERVICE_NAME
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: websecret
              key: HONEYCOMB_API_KEY
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /live
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 30
