apiVersion: v1
kind: Secret
metadata:
  name: cronsecret
  namespace: newsfeed
type: Opaque
data:
  DB_CONN: ${DB_CONN}
  DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronconfigmap
  namespace: newsfeed
data:
  GRPC_SERVER_ADDRESS: 192.168.1.7:30008
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: newsfeed-cronjob
  namespace: newsfeed
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: newsfeed-cronjob
            image: edisonlt/cron-feed:latest
            resources:
              limits:
                memory: "200Mi"
              requests:
                memory: "100Mi"
            env:
            - name: DB_CONN
              valueFrom:
                secretKeyRef:
                  name: cronsecret
                  key: DB_CONN
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: cronsecret
                  key: DISCORD_WEBHOOK
            - name: GRPC_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: cronconfigmap
                  key: GRPC_SERVER_ADDRESS
          restartPolicy: OnFailure
