apiVersion: v1
kind: Secret
metadata:
  name: cronsecret
  namespace: newsfeed
type: Opaque
data:
  DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronconfigmap
  namespace: newsfeed
data:
  GRPC_SERVER_ADDRESS: 192.168.1.7:30008
  OTEL_SERVICE_NAME: "newsfeed-cronjob"
  OTEL_EXPORTER_OTLP_GRPC_ENDPOINT: "192.168.1.6:4317"
  LOKI_GRPC_ADDRESS: "192.168.1.6:9096"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: newsfeed-cronjob
  namespace: newsfeed
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: newsfeed-cronjob
            image: edisonlt/cron-feed:latest
            resources:
              limits:
                memory: "200Mi"
              requests:
                memory: "100Mi"
            env:
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: cronsecret
                  key: DISCORD_WEBHOOK
            - name: GRPC_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: cronconfigmap
                  key: GRPC_SERVER_ADDRESS
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cronconfigmap
                  key: OTEL_SERVICE_NAME
            - name: OTEL_EXPORTER_OTLP_GRPC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: cronconfigmap
                  key: OTEL_EXPORTER_OTLP_GRPC_ENDPOINT
            - name: LOKI_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: cronconfigmap
                  key: LOKI_GRPC_ADDRESS
          restartPolicy: OnFailure
